service: ezyraise
variablesResolutionMode: 20210326
provider:
  lambdaHashingVersion: 20201221
  name: aws
  stage: production
  memorySize: 512
  timeout: 900
  region: us-west-2
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ssm:GetParameter'
          Resource:
            - 'arn:aws:ssm:${self:provider.region}:*:parameter/*'

plugins:
  - serverless-offline

package:
  individually: true

functions:
  getScheduledCampaigns:
    handler: src/handler.getScheduledCampaigns
    events:
      - schedule: rate(1 hour)